development:
  host: localhost
  database: with_development

test:
  host: localhost
  database: with_test

# set these environment variables on your prod server
production:
    #uri: <%= ENV['MONGOHQ_URL'] %>
    #uri: <%= "mongodb://test:test@staff.mongohq.com:10079/app3036868"  %>

    sessions:
      default:
        uri: <%= ENV['MONGOHQ_URL'] %>
        options:
          skip_version_check: true
          safe: true

    #
    # 
    # host: <%= ENV['MONGOID_HOST'] %>
    # port: <%= ENV['MONGOID_PORT'] %>
    # username: <%= ENV['MONGOID_USERNAME'] %>
    # password: <%= ENV['MONGOID_PASSWORD'] %>
    # database: <%= ENV['MONGOID_DATABASE'] %>    
    # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
